name: Package linting

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
      - ci-debug

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: 30.1

      - uses: conao3/setup-cask@master
        with:
          version: 'snapshot'

      - name: Install dependencies
        run: '$HOME/.cask/bin/cask install'

      - name: Byte compile files
        run: '$HOME/.cask/bin/cask build'

      - name: Package lint
        run: 'cask emacs -Q -batch -f package-lint-batch-and-exit *.el'

      - name: Checkdoc
        run: |
          for FILE in *.el
          do cask emacs -batch \
              -eval "(setq checkdoc-verb-check-experimental-flag nil)" \
              -eval "(checkdoc-file \"${FILE}\")"
          done
